### ISSUE TITLE
18 - useLocalStorage

### ISSUE THREAD

**Issue by chenbowu** [webfansplz/vuejs-challenges#1210]
```vue
<script setup lang='ts'>

import { ref, watchEffect } from "vue"

/**
 * Implement the composable function
 * Make sure the function works correctly
*/
function useLocalStorage(key: string, initialValue: any) {
  initialValue = localStorage.getItem(key) || value.value
  const value = ref(initialValue)
	watchEffect(() => {
    localStorage.setItem(key, value.value)
  })
  return value
}

const counter = useLocalStorage("counter", 0)

// We can get localStorage by triggering the getter:
console.log(counter.value)

// And we can also set localStorage by triggering the setter:

const update = () => counter.value++

</script>

<template>
  <p>Counter: {{ counter }}</p>
  <button @click="update">
    Update
  </button>
</template>

```

**Comment by jxxl998** [comment]
hi! I'm new to Vue3, inside of the useLocalStorage function, what's the meaning of  ` value.value` when assigning to param `initialValue`?  thx :)

**Comment by chenbowu** [comment]
> hi! I'm new to Vue3, inside of the useLocalStorage function, what's the meaning of ` value.value` when assigning to param `initialValue`? thx :)

`ref` function takes an inner value and returns a reactive and mutable ref object, which has a single property .value that points to the inner value.

Because the useLocalStorage function may pass in an inner type, use ref to create a reactive object.

You can see more at https://vuejs.org/api/reactivity-core.html#ref

**Comment by Lazygui** [comment]
> ```
> <script setup lang='ts'>
> 
> import { ref, watchEffect } from "vue"
> 
> /**
>  * Implement the composable function
>  * Make sure the function works correctly
> */
> function useLocalStorage(key: string, initialValue: any) {
> //value.value在ts里会提示{value 还没有被定义。}
>  //initialValue = localStorage.getItem(key) || value.value
> //改为以下会更好
>   const value = ref(localStorage.getItem(key) ||initialValue)
> 	watchEffect(() => {
>     localStorage.setItem(key, value.value)
>   })
>   return value
> }
> 
> const counter = useLocalStorage("counter", 0)
> 
> // We can get localStorage by triggering the getter:
> console.log(counter.value)
> 
> // And we can also set localStorage by triggering the setter:
> 
> const update = () => counter.value++
> 
> </script>
> 
> <template>
>   <p>Counter: {{ counter }}</p>
>   <button @click="update">
>     Update
>   </button>
> </template>
> ```
