### ISSUE TITLE
25 - useMouse

### ISSUE THREAD

**Issue by chenbowu** [webfansplz/vuejs-challenges#1224]
```vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
// Implement ...
function useEventListener(target, event, callback) {
  // 注意要移除事件
  onMounted(() => {
    target.addEventListener(event, callback)
  })
	onUnmounted(() => {
    target.removeEventListener(event, callback)
  })
}

// Implement ...
function useMouse() {
  const x = ref(0)
  const y = ref(0)
  useEventListener(window, "mousemove", (e) => {
    x.value = e.clientX
    y.value = e.clientY
  })
  return {
    x, y
  }
}
const { x, y } = useMouse()
</script>

<template>Mouse position is at: {{ x }}, {{ y }}</template>

```

**Comment by zgsgs** [comment]
请问有没有遇到，代码可以正常运行，测试不通过的情况

![image](https://github.com/webfansplz/vuejs-challenges/assets/22882957/66a13620-0400-4c77-81be-9a5517edac54)

请问这种问题有解决办法吗？

**Comment by VinTurtle** [comment]
> 请问有没有遇到，代码可以正常运行，测试不通过的情况
> 
> ![image](https://private-user-images.githubusercontent.com/22882957/242246945-66a13620-0400-4c77-81be-9a5517edac54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjUzNzcsIm5iZiI6MTcwMjYyNTA3NywicGF0aCI6Ii8yMjg4Mjk1Ny8yNDIyNDY5NDUtNjZhMTM2MjAtMDQwMC00Yzc3LTgxYmUtOWE1NTE3ZWRhYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTU4YTA5MTM0NTY0M2VlYTYyN2IwYWUxODc1ZWIzYjIyM2Q5ZjI2YWE4YzBhYWRmMmQ2YjMwZDczZjU4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MqJWjWep5x70qmOQPlBSjONHL0Ace05ETMAf9UiU2N4)
> 
> 请问这种问题有解决办法吗？

遇到同样的问题，有解决方案吗

**Comment by chenbowu** [comment]
> > 请问有没有遇到，代码可以正常运行，测试不通过的情况
> > ![image](https://private-user-images.githubusercontent.com/22882957/242246945-66a13620-0400-4c77-81be-9a5517edac54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MjUzNzcsIm5iZiI6MTcwMjYyNTA3NywicGF0aCI6Ii8yMjg4Mjk1Ny8yNDIyNDY5NDUtNjZhMTM2MjAtMDQwMC00Yzc3LTgxYmUtOWE1NTE3ZWRhYzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDA3MjQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4OTU4YTA5MTM0NTY0M2VlYTYyN2IwYWUxODc1ZWIzYjIyM2Q5ZjI2YWE4YzBhYWRmMmQ2YjMwZDczZjU4OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MqJWjWep5x70qmOQPlBSjONHL0Ace05ETMAf9UiU2N4)
> > 请问这种问题有解决办法吗？
> 
> 遇到同样的问题，有解决方案吗

代码贴上来看看
