### ISSUE TITLE
21 - 函数式组件

### ISSUE THREAD

**Issue by mahao1** [webfansplz/vuejs-challenges#1298]
```
<script setup lang='ts'>

import { ref, h } from "vue"

/**
 * Implement a functional component :
 * 1. Render the list elements (ul/li) with the list data
 * 2. Change the list item text color to red when clicked.
*/
const ListComponent = (props, { emit }) => {
  const childs = []
  
  props.list.map((item, index)=>{
    childs.push(
    	h('li', {
        	style: {
            color: index === props['active-index'] ? 'red' : '#333'
          },
        	onclick: ()=>{
            emit('toggle', index)
          }
      }, item.name)
    )
  })
  
  return h('ul', childs)
}

const list = [{
  name: "John",
}, {
  name: "Doe",
}, {
  name: "Smith",
}]

const activeIndex = ref(0)

function toggle(index: number) {
  activeIndex.value = index
}

</script>

<template>
  <list-component
    :list="list"
    :active-index="activeIndex"
    @toggle="toggle"
  />
</template>

```

**Comment by mahao1** [comment]
> <script setup lang='ts'> import { ref, h } from "vue" /** * Implement a functional component : * 1. Render the list elements (ul/li) with the list data * 2. Change the list item text color to red when clicked. */ const ListComponent = (props, { emit }) => { const childs = [] props.list.map((item, index)=>{ childs.push( h('li', { style: { color: index === props['active-index'] ? 'red' : '#333' }, onclick: ()=>{ emit('toggle', index) } }, item.name) ) }) return h('ul', childs) } const list = [{ name: "John", }, { name: "Doe", }, { name: "Smith", }] const activeIndex = ref(0) function toggle(index: number) { activeIndex.value = index } </script>

**Comment by elderdog** [comment]
Hi, nice answer, while there is something can be improved that I'd like to point out

1. better to announce ListComponent.props = ['list', 'active-index']
2. naming childs -> children
3. always return someting in Array.map or you can use Array.forEach here
4. should consider test case `expect(inactive_item.attributes("style")).toBeUndefined()`
