### ISSUE TITLE
render function: h()

### ISSUE THREAD

**Issue by murongg** [webfansplz/vuejs-challenges#218]
## Info

Basic info of your challenge questions,

```yaml
difficulty: medium
title: render function: h()
tags: Components
```

## Question

For this challenge, you need use `h` render function implement a component. It is important to note that you must make sure that the props are passed correctly、event triggered normally and slot content rendering is normal. let’s go.

```vue
<script setup lang="ts">
import MyButton from "./MyButton"

const myClick = () => {
  console.log('myClick')
}

</script>

<template>
  <MyButton :disabled="false" @myClick="myClick">
    my button
  </MyButton>
</template>
```

## Template

filename: App.vue

```vue
<script setup lang="ts">
import MyButton from "./MyButton"

const myClick = () => {
  console.log('myClick')
}

</script>

<template>
  <MyButton :disabled="false" @myClick="myClick">
    my button
  </MyButton>
</template>
```

filename: MyButton.ts

```ts
import { defineComponent } from "vue"

export default defineComponent({
  name: 'MyButton',
  render() {
    return h(/** do someting */)
  }
})
```

**Comment by murongg** [comment]
> `h函数`这个题目的名字会有点泛,很容易重复,这边建议改成 (按钮组件)`button component`,然后`h`函数来实现在描述里体现就可以. (可以尝试直接更新issue看看pr会不会udpate,昨天有点问题),另外我觉得这个的问题难度应该是`medium`

我刚才尝试修改了 issue，GitHub Actions 正确执行了

**Comment by webfansplz** [comment]
> @webfansplz 这个中英文翻译器也有点问题，建议把中/英文放到一个 issue 由出题者提交

翻译器只在一定程度上做参考,这个我这边来校对就好了,更希望贡献者只需要关注自己的语言部分就好,降低成本. (外国友人贡献中文版本也有点麻烦)

**Comment by webfansplz** [comment]
> > `h函数`这个题目的名字会有点泛,很容易重复,这边建议改成 (按钮组件)`button component`,然后`h`函数来实现在描述里体现就可以. (可以尝试直接更新issue看看pr会不会udpate,昨天有点问题),另外我觉得这个的问题难度应该是`medium`
> 
> 如果使用 `button-component` ，单纯以题目名称而言，不太足以成为一个 `hard` 题目。 而且是不是不太能从题目名称上 get 到题目的考点，从而使挑战者对此题目提不起兴趣。 挑战者很容可能认为这是一个很普通的 button 组件。

我认同这个观点, 改为 render function (h),渲染函数 (h)会更好,另外难度我觉得还是应该在`medium`, 同 [21-functional-component](https://github.com/webfansplz/vuejs-challenges/blob/main/questions/21-functional-component/README.md)

**Comment by webfansplz** [comment]
> > > > `h函数`这个题目的名字会有点泛,很容易重复,这边建议改成 (按钮组件)`button component`,然后`h`函数来实现在描述里体现就可以. (可以尝试直接更新issue看看pr会不会udpate,昨天有点问题),另外我觉得这个的问题难度应该是`medium`
> > > 
> > > 
> > > 如果使用 `button-component` ，单纯以题目名称而言，不太足以成为一个 `hard` 题目。 而且是不是不太能从题目名称上 get 到题目的考点，从而使挑战者对此题目提不起兴趣。 挑战者很容可能认为这是一个很普通的 button 组件。
> > 
> > 
> > 我认同这个观点, 改为 render function (h),渲染函数 (h)会更好,另外难度我觉得还是应该在`medium`, 同 [21-functional-component](https://github.com/webfansplz/vuejs-challenges/blob/main/questions/21-functional-component/README.md)
> 
> render function (h) 还是说 render function h() 好些，`medium ` 认同

render function : h()

**Comment by murongg** [comment]
> > > > > `h函数`这个题目的名字会有点泛,很容易重复,这边建议改成 (按钮组件)`button component`,然后`h`函数来实现在描述里体现就可以. (可以尝试直接更新issue看看pr会不会udpate,昨天有点问题),另外我觉得这个的问题难度应该是`medium`
> > > > 
> > > > 
> > > > 如果使用 `button-component` ，单纯以题目名称而言，不太足以成为一个 `hard` 题目。 而且是不是不太能从题目名称上 get 到题目的考点，从而使挑战者对此题目提不起兴趣。 挑战者很容可能认为这是一个很普通的 button 组件。
> > > 
> > > 
> > > 我认同这个观点, 改为 render function (h),渲染函数 (h)会更好,另外难度我觉得还是应该在`medium`, 同 [21-functional-component](https://github.com/webfansplz/vuejs-challenges/blob/main/questions/21-functional-component/README.md)
> > 
> > 
> > render function (h) 还是说 render function h() 好些，`medium ` 认同
> 
> render function : h()

那就使用这个名字吧！

**Comment by webfansplz** [comment]
> 还有一个问题就是：我上一个提交的挑战 `Tree Component`， <img alt="image" width="1260" src="https://user-images.githubusercontent.com/38655613/177348533-3d2b46f6-a266-4e72-80dc-ebfe99385a86.png"> readme.md 没有代码模板，还是说这个题目不需要模板。

这块是由提案者在`Question`部分补充的,至于需不需要可以先取决于提案者,是一个可选项.

**Comment by webfansplz** [comment]
我看到题目的`prop`参数是`disabled`,然后又传递了一个双击事件, 这是不是冲突了 (禁用状态不应该触发事件)
