### ISSUE TITLE
15 - 切换器

### ISSUE THREAD

**Issue by Sevichecc** [webfansplz/vuejs-challenges#959]
```vue
<script setup lang="ts">
import { ref } from 'vue';
/**
 * Implement a composable function that toggles the state
 * Make the function work correctly
 */
function useToggle(init: boolean) {
  const state = ref(init);
  const toggle = () => state.value = !state.value;
  return [state, toggle];
}

const [state, toggle] = useToggle(false);
</script>

<template>
  <p>State: {{ state ? 'ON' : 'OFF' }}</p>
  <p @click="toggle">Toggle state</p>
</template>

```

**Comment by Lazygui** [comment]
<script setup lang='ts'>
import { ref } from 'vue'
// 需要定义返回值的类型
// 不定义ts会提示但不影响运行
const useToggle = (initState: boolean = false): [Ref<boolean>, () => void] => {
     const state = ref(initState)
     const toggle = (): void => { state.value = !state.value }
     return [
          state,
          toggle
     ]
}

const [state, toggle] = useToggle()
</script>

<template>
     
     <div>
          <p>State: {{ state ? 'ON' : 'OFF' }}</p>
          <p @click="toggle">
               Toggle state
          </p>
     </div>
</template>

**Comment by Lazygui** [comment]
> ```
> <script setup lang="ts">
> import { ref } from 'vue';
> // 需要定义返回值的类型
> // 不定义ts会提示但不影响运行
> const useToggle = ((init: boolean = false): [Ref<boolean>, () => void] => {
>   const state = ref(init);
>   const toggle = (): void => { state.value = !state.value }
>   return [state, toggle];
> }
> 
> const [state, toggle] = useToggle(false);
> </script>
> 
> <template>
> 
>  <div>
>   <p>State: {{ state ? 'ON' : 'OFF' }}</p>
>   <p @click="toggle">Toggle state</p>
>  </div>
> </template>
> ```
